apiVersion: apps/v1
kind: Deployment
metadata:
  name: livros-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livros-api
  template:
    metadata:
      labels:
        app: livros-api
    spec:
      containers:
      - name: livros-api
        image: livros-api:latest
        imagePullPolicy: Never
        ports:
        - containersPort: 8000
        env:
        - name: DATABASE_URL
          value: "sqlite:///./livros.db"
        - name: MEU_USUARIO
          value: "admim"
        - name: MINHA_SENHA
          value: "admim"